#!/bin/bash
clear
echo "ddw 2.5"
update() {
	echo "Updateing ddw"
	sudo wget https://raw.githubusercontent.com/SkywalkerSW5/ddw/master/ddw 
	sudo chmod +x ./ddw

}
usage() {
	echo 
	echo "Usage:"
	echo
	echo "ddw iso: Writes selected iso to selected drive"
	echo
	echo "ddw port: Opens selected port;"

}
port() {
	echo "Enter the number of the port you wanna open"
	read port
	echo "Opening port " $port
	echo "Port opened"
	netcat -l -k $port
	}
mount() {
	echo "Enter the filename of the ISO"
	read iso
	cd 
	sudo mkdir iso-mount
	sudo mount ./iso-mount $iso
	cd -
}
iso() {
	clear
	echo "Enter the filename of the ISO:" && read iso
	echo "Enter the filename of the device:" && read device
	sudo dd if=$iso of=$device status=progress
}

 if [ -z "$*" ]; then 
	echo "Run ddw usage for usage info"; fi

for a in $@; do
    case $a in
        "") echo;;
        "iso") iso;;
        "usage") usage;;
        "help") usage;;
	"update") update;;
	"port") port;;
        *)
            
    esac
done
